"""initial schema

Revision ID: 050a644df84f
Revises: 
Create Date: 2026-08-16 07:18:50.287939
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '050a644df84f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('self_esteem', sa.Integer(), nullable=False),
    sa.Column('mental_health_history', sa.Integer(), nullable=False),
    sa.Column('headache', sa.Integer(), nullable=False),
    sa.Column('breathing_problem', sa.Integer(), nullable=False),
    sa.Column('noise_level', sa.Integer(), nullable=False),
    sa.Column('living_conditions', sa.Integer(), nullable=False),
    sa.Column('safety', sa.Integer(), nullable=False),
    sa.Column('basic_needs', sa.Integer(), nullable=False),
    sa.Column('academic_performance', sa.Integer(), nullable=False),
    sa.Column('study_load', sa.Integer(), nullable=False),
    sa.Column('teacher_student_relationship', sa.Integer(), nullable=False),
    sa.Column('social_support', sa.Integer(), nullable=False),
    sa.Column('peer_pressure', sa.Integer(), nullable=False),
    sa.Column('extracurricular_activities', sa.Integer(), nullable=False),
    sa.Column('predicted_class', sa.Integer(), nullable=False),
    sa.Column('predicted_probabilities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('model_version', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_created_at'), 'assessments', ['created_at'], unique=False)
    op.create_index(op.f('ix_assessments_user_id'), 'assessments', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age_group', sa.String(length=16), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('degree_field', sa.String(length=128), nullable=True),
    sa.Column('year_of_study', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('explanation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paragraph', sa.Text(), nullable=False),
    sa.Column('faithfulness_factors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('coverage_ratio', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_explanation_records_assessment_id'), 'explanation_records', ['assessment_id'], unique=True)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_affirmation', sa.Boolean(), nullable=False),
    sa.Column('affirmation_text', sa.Text(), nullable=True),
    sa.Column('adaptive_recovery_applied', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_assessment_id'), 'recommendations', ['assessment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_assessment_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_explanation_records_assessment_id'), table_name='explanation_records')
    op.drop_table('explanation_records')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_assessments_user_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_created_at'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
