"""add adaptive recovery framework

Revision ID: 3e72333cb8f4
Revises: 050a644df84f
Create Date: 2026-08-16 23:28:05.830423
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3e72333cb8f4'
down_revision: Union[str, None] = '050a644df84f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - hand-adjusted, see notes below ###
    #
    # Both new NOT NULL columns need a server_default for this ALTER to
    # succeed against any assessments/recommendations rows that already
    # exist (2 did, from earlier manual endpoint testing, predating the
    # Adaptive Recovery Framework entirely). 'no_previous_checkin' is the
    # honest backfill value for previous_engagement: those rows have no
    # engagement data available, which is exactly what that value means.
    # is_escalation=False is unambiguous for the same reason.
    #
    # The server defaults are dropped immediately after backfilling, so every
    # future insert must supply both values explicitly via the application —
    # neither ORM model declares a Python-level default — rather than
    # silently falling back to one that would mask a real bug upstream.
    op.add_column(
        'assessments',
        sa.Column(
            'previous_engagement',
            sa.String(length=20),
            nullable=False,
            server_default='no_previous_checkin',
        ),
    )
    op.add_column(
        'recommendations',
        sa.Column('is_escalation', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column('recommendations', sa.Column('escalation_message', sa.Text(), nullable=True))
    op.add_column('recommendations', sa.Column('adaptive_recovery_reason', sa.Text(), nullable=True))

    op.alter_column('assessments', 'previous_engagement', server_default=None)
    op.alter_column('recommendations', 'is_escalation', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'adaptive_recovery_reason')
    op.drop_column('recommendations', 'escalation_message')
    op.drop_column('recommendations', 'is_escalation')
    op.drop_column('assessments', 'previous_engagement')
    # ### end Alembic commands ###
